// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ckjtusercmvsucqvnizk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNranR1c2VyY212c3VjcXZuaXprIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwNjgyOTYsImV4cCI6MjA2NjY0NDI5Nn0.nTotWzYYU2MqdUZn2Q8hoTHgCG5fq4YJerHnVmhIuPw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);